import "./globals.css";

export const metadata = {
  title: "Techtonic Labs",
  description: "Generated by Techtonic Lab Private Limited",
};
import {Outfit } from 'next/font/google'

const outfit = Outfit({
  weight: ['400','500','600','700'],
  subsets: ['latin'],
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${outfit.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
