import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Techtonic Labs",
  description: "Generated by Techtonic Lab Private Limited",
};
import {Outfit } from 'next/font/google'

const outfit = Outfit({
  weight: ['400','500','600','700'],
  subsets: ['latin'],
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script id="google-tag-manager" strategy="afterInteractive">
          {
            `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TWTQ48H3')`
          }
        </Script>
      </head>
      <body
        className={` ${outfit.className} antialiased`}
      >
        <noscript dangerouslySetInnerHTML={{
          __html:`<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TWTQ48H3"
height="0" width="0" style="display:none;visibility:hidden"></iframe>`
        }} />
        {children}
      </body>
    </html>
  );
}
